GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWsxMiIsImlkIjoiNjkyZWQzZGZhNGI3YzBjMDE0ODU4MmU1IiwiaWF0IjoxNzY0NjgxMjg0fQ.jPbXs5gWoLUWfufyrcId3N82TWWbOzAIMPx4ClkOZYA

{
    "title": "2 Another course of JWT and Authorization header",
    "author": "University of Helsinki",
    "url": "https://example.com/",
    "likes": "10"
}